services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: nextjs-app # Comentado para evitar conflictos de nombre en despliegues mÃºltiples
    restart: always
    ports:
      - "3005:3000" # Mapea puerto 3005 del host -> 3000 del contenedor
    environment:
      - NODE_ENV=production
