services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: nextjs-app # Comentado para evitar conflictos de nombre en despliegues m√∫ltiples
    restart: always
    env_file:
      - .env
    labels:
      - traefik.http.middlewares.auth.basicauth.users=mati:$$apr1$$4yPRDSG8$$odHpHi9Zwat0DnUBh7IrP0
      - traefik.http.routers.mcphotels-testflowhotels-8kzfd1-87-web.middlewares=auth
      - traefik.http.routers.mcphotels-testflowhotels-8kzfd1-87-websecure.middlewares=auth